ARM-software/CMSIS_6

CMSIS/CoreValidation/Layer/App/Validation_Cortex-A/App.clayer.yml
CMSIS/CoreValidation/Layer/App/Validation_Cortex-M/App.clayer.yml
CMSIS/Core_A/Include/cmsis_gcc.h

At -O0 the pseudo instruction LDR R2,=0x00086060
caused the literal pool to be created out of range.

Fix GCC's __FPU_Enable for Cortex-A for no optimisation

---

CMSIS/Core/Include/cmsis_compiler.h
CMSIS/CoreValidation/Project/build.py
CMSIS/CoreValidation/Source/CV_CoreAFunc.c
CMSIS/CoreValidation/Source/CV_CoreFunc.c
CMSIS/CoreValidation/Source/CV_CoreInstr.c
CMSIS/CoreValidation/Source/CV_CoreSimd.c
CMSIS/CoreValidation/Source/CV_GenTimer.c

cmsis_compiler.h must be independent from being included after core_xx.h which sets __CORTEX_x defines.

Fix arch profile detection

---

ARM.CMSIS.pdsc

OS Tick belongs to CMSIS rather than to Device class.
It also solves the issue when Device class uses bundles and Device:OS Tick would not be part of the bundle.

OS Tick: moved from Device to CMSIS class

---

ARM.CMSIS.pdsc
CMSIS/Core/Include/cmsis_version.h
CMSIS/Core/Include/core_ca.h
CMSIS/Core/Include/core_cm0.h
CMSIS/Core/Include/core_cm0plus.h
CMSIS/Core/Include/core_cm1.h
CMSIS/Core/Include/core_cm23.h
CMSIS/Core/Include/core_cm3.h
CMSIS/Core/Include/core_cm33.h
CMSIS/Core/Include/core_cm35p.h
CMSIS/Core/Include/core_cm4.h
CMSIS/Core/Include/core_cm55.h
CMSIS/Core/Include/core_cm7.h
CMSIS/Core/Include/core_cm85.h
CMSIS/Core/Include/core_sc000.h
CMSIS/Core/Include/core_sc300.h
CMSIS/Core/Include/core_starmc1.h
CMSIS/Core/Include/tz_context.h
CMSIS/RTOS2/Source/os_systick.c

Reworked CMSIS core header files:
- align with latest TRMs
- unified core header

Cortex(M): align core header with TRMs

---

CMSIS/Documentation/Doxygen/gen_doc.sh
gen_pack.sh

Use same version of gen-pack library for gen_pack.sh and gen_doc.sh as used by check_links.sh

Pack generation: Use same version of gen-pack library

---

CMSIS/Core/Include/m-profile/cmsis_iccarm_m.h

* Update __NO_RETURN macro to not require IAR language extensions. Hopefully this is backwards compatible enough.
* Add __ARM_ARCH_8_1M_MAIN__ and always check for it when checking for __ARM_ARCH_8_MAIN__.
These macros generate so many questions for me that I don't have good answers for. 
I am happy to work on this file further but I just wanted to fix these issues first.

Update __NO_RETURN Macro. Add ARMv8.1-M Support

---

CMSIS/Core/Include/m-profile/cmsis_armclang_m.h
CMSIS/Documentation/Doxygen/Core/src/ref_compiler_ctrl.txt

Added `.bss` at beginning of the section name as required by Arm Compiler 6.
Clarified description of the macro in the documentation.

Core: Update __NO_INIT docu and implementation for AC6

---

CMSIS/Core/Include/m-profile/cmsis_iccarm_m.h

So we replace with inline assembly
NOTE: This function has been pretty confusing for everyone involved.
It boils down to "cpsid f/cpsie f" which is identical on Cortex-A (which talks about IRQs and Fast IRQs (fiq)) and Cortex-M which talks about fault irqs.
This means it was internally handled the same way on both architectures. And using it as an intrinsic was fine until
IAR 9.40 stopped supporting enable_fiq/disable_fiq on Cortex-M. (EWARM-10800)

__enable/disable_fiq is forbidden on Cortex-M since IAR 9.40.1.

---

CMSIS/Core/Include/m-profile/cmsis_iccarm_m.h

There are some issues with header include order and this makes FPSCR intrinsic fail on IAR.
We change it to use compiler ACLE defines instead.

Use __ARM_FP to detect FPU

---

CMSIS/Core/Include/a-profile/cmsis_armclang_a.h
CMSIS/Core/Include/a-profile/cmsis_clang_a.h
CMSIS/Core/Include/a-profile/cmsis_gcc_a.h
CMSIS/Core/Include/m-profile/cmsis_armclang_m.h
CMSIS/Core/Include/m-profile/cmsis_gcc_m.h

Both versions (Cortex-M and Cortex-A) are better comparable now.
Compare also https://github.com/ARM-software/CMSIS_5/pull/1587

Core(A): align compiler header files to core(M) implementation

---

CMSIS/CoreValidation/Layer/Target/CM0/model_config.txt
CMSIS/CoreValidation/Layer/Target/CM0plus/model_config.txt
CMSIS/CoreValidation/Layer/Target/CM7/model_config.txt

update model configuration used in CoreValidation to support devices from Cortex_DFP

Core: align CoreValidation model configuration with Cortex_DFP

---

CMSIS/CoreValidation/Source/CV_CML1Cache.c
CMSIS/CoreValidation/Source/Config/CV_Config.h

Updated use of  #ifdef __ICACHE_PRESENT, #ifdef __DCACHE_PRESENT

Core: corrected use of #ifdef __ICACHE_PRESENT / __DCACHE_PRESENT (#134)

---

CMSIS/CoreValidation/Layer/Target/CM0/RTE/Device/ARMCM0/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM0plus/RTE/Device/ARMCM0P/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM23/RTE/Device/ARMCM23/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM23NS/RTE/Device/ARMCM23/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM23S/RTE/Device/ARMCM23/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM3/RTE/Device/ARMCM3/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM33/RTE/Device/ARMCM33/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM33NS/RTE/Device/ARMCM33/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM33S/RTE/Device/ARMCM33/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM35P/RTE/Device/ARMCM35P/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM35PNS/RTE/Device/ARMCM35P/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM35PS/RTE/Device/ARMCM35P/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM4/RTE/Device/ARMCM4/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM52/RTE/Device/ARMCM52/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM52NS/RTE/Device/ARMCM52/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM52S/RTE/Device/ARMCM52/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM55/RTE/Device/ARMCM55/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM55NS/RTE/Device/ARMCM55/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM55S/RTE/Device/ARMCM55/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM7/RTE/Device/ARMCM7/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM85/RTE/Device/ARMCM85/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM85NS/RTE/Device/ARMCM85/iar_linker_script.icf
CMSIS/CoreValidation/Layer/Target/CM85S/RTE/Device/ARMCM85/iar_linker_script.icf

Note: This bug was from CMSIS-Toolbox which was fixed (https://github.com/Open-CMSIS-Pack/devtools/pull/1378).

Fix typos in IAR linker scripts for Cortex-M in ROM1 and RAM1

---

CMSIS/Documentation/Doxygen/Core/src/ref_cm4_simd.txt

`__UQADD8` and `__UADD8` incorrectly claimed their return values contain halved results, but that is not the case.

Fix __UQADD8 and __UADD8 return value descriptions

---

CMSIS/Core/Include/core_cm7.h

Added again LAR, LSR register to Cortex-M7 DWT

Core: added LAR, LSR register to DWT

---

CMSIS/Core/Include/m-profile/cmsis_armclang_m.h
CMSIS/Core/Include/m-profile/cmsis_clang_m.h
CMSIS/Core/Include/m-profile/cmsis_gcc_m.h
CMSIS/Core/Include/m-profile/cmsis_tiarmclang_m.h

Check if macro __ARM_FEATURE_CMSE is defined before evaluating it's value

Core: added define guard __ARM_FEATURE_CMSE (#171)

---

CMSIS/Core/Include/core_cm33.h

Update core_cm33.h, spelling fixup - writen==>written

---

CMSIS/Core/Include/core_cm55.h
CMSIS/Core/Include/core_cm85.h

FP & MVE requires the SU10 to be modified while transitioning to low power state.
Add support for SU10/S11 register fields.

CMSIS-Core(M): M55/M85 : add CPPWR SU10/11 defines

---

ARM.CMSIS.pdsc

Fixes ARM-software/CMSIS_6#201

Include tz_context.h header only if TrustZone is available and used but not switched off.

---

CMSIS/Documentation/Doxygen/Toolbox/src/mainpage.md

Replaced references to https://github.com/Open-CMSIS-Pack/cmsis-toolbox/... to https://open-cmsis-pack.github.io/cmsis-toolbox/ a.o
[Issue 248](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/248)

Replaced references

---

CMSIS/Documentation/Doxygen/Core_A/src/ref_gic.txt

Fix documentation of the Register HPPIR_INTID according to
"ARM Generic Interrupt Controller Architecture version 2.0 Architecture Specification"
Table 4-41 GICC_HPPIR bit assignments

Fix documentation of the Register HPPIR_INTID

---

CMSIS/Core/Include/cmsis_gcc.h

AArch64 GCC does not have the __builtin_arm_set_fpscr() and __builtin_arm_get_fpscr() functions.
https://gcc.gnu.org/onlinedocs/gcc/AArch64-Built-in-Functions.html
Use the same ASM inserts as before commit 30e56dafebc6d5427d68e8fde2307b1114b6a01a.

fix AArch64 GCC FPSCR intrinsics
